# Generated by Django 2.2 on 2021-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=5000)),
                ('link', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
