# Generated by Django 2.2 on 2021-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='desc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
