# Generated by Django 2.2 on 2021-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210427_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tilte',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
