# Generated by Django 2.2 on 2021-05-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='eamil',
            new_name='email',
        ),
    ]
