# Generated by Django 2.2 on 2021-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=5000)),
                ('link', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
