# Generated by Django 2.2 on 2021-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_contribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(default=True),
        ),
    ]
