# Generated by Django 2.2 on 2021-06-12 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20210612_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='bp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Blogpost'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='link',
            field=models.URLField(default=True),
        ),
    ]
