# Generated by Django 2.2 on 2021-06-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_auto_20210612_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='desc',
        ),
    ]
