# Generated by Django 2.2 on 2021-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_remove_youtube_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='desc',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
